### ISSUE TITLE
Can't resolve './generated/regexVisitor', './generated/regexLexer' and './generated/regexParser'

### ISSUE THREAD

**Issue by fcnow** [DanielBV/RegexEngine#1]
When run npm start, it will report
Compiled with problems:
ERROR in ./src/grammar/astBuilder.js 39:0-52
Module not found: Error: Can't resolve './generated/regexVisitor' in '{path}\RegexEngine\src\grammar'
ERROR in ./src/grammar/parser.js 26:0-48
Module not found: Error: Can't resolve './generated/regexLexer' in '{path}\RegexEngine\src\grammar'
ERROR in ./src/grammar/parser.js 27:0-50
Module not found: Error: Can't resolve './generated/regexParser' in '{path}\RegexEngine\src\grammar'

Although these files can be generated using antlr, it will be more convenient to include it. Could you please include it?

**Comment by DanielBV** [comment]
Hi, sorry for the late reply. The message got sent to spam and I don't enter Github frequently 😭.
I just included it, thanks for the suggestion
